= UPDATE-PASSWD(1) =

== NAME ==
update-passwd - add user and group entries for daemons

== SYNOPSIS ==
*update-passwd* *-n* <Short-Name> *-g* <Group-Name> [*-h* <Home-Dir>] [*-s* <Shell>] *-i* <Info-String> *-m* <Group-Members>

*update-passwd* *-g* <Group-Name> *-m* <Group-Members>

*update-passwd* *-V*

== DESCRIPTION ==
Adds user and group entries for daemons.

This program is meant to be used by the fink package manager to setup necessary
users and groups for other packages.  It is meant to be called by independent
packages for each user/group.

By default it reuses any existing users/groups on the system that match the
calling requirements.  This includes adding aliases for close matches such as
`<user/group>` -> `_<user/group>`.  If a matching user/group is not found it
will create one with dynamically allocated ids as specified in the `passwd.conf`
file. If this functionality is turned off it will fall back to the lists
maintained in the `group-fink.conf` and `passwd-fink.conf` files.

== OPTIONS ==

*-n* '<short-name>'::
Sets the user short name.  It is required to make a user.

*-g* '<group-name>'::
Sets the name of the (primary) group. (Always Required)

*-h* '<home-dir>'::
Sets the home directory path (optional).  If not set `/var/empty` will be used.

*-s* '<shell>'::
Sets the path to login shell (optional).  If not set `/usr/bin/false` will be used.

*-i* '<info-string>'::
Sets the long discription of the user and/or group. (Required for Users)

*-m* '<group-members>'::
A comma separated list of group membersips by name.  (Always Required)

*-V*::
Emits the update-passwd version and exits.

== Notes ==
Development of autorevision is carried out at
https://github.com/fink/passwd

== AUTHORS ==

See AUTHORS.txt for a full list in order of number of contributions.
